-- Add new columns to employers table
ALTER TABLE employers
ADD COLUMN IF NOT EXISTS company_size TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS ceo TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS founded_year INTEGER,
ADD COLUMN IF NOT EXISTS headquarters TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS branches TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS benefits TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS technologies TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS company_culture TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS office_images TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS employee_count INTEGER;

-- Add new columns to jobs table
ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS work_mode TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS responsibilities TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS department TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS education_requirement TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS benefits TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS stipend JSONB DEFAULT '{}';
